services:
  api:
    # TODO: drop env_file, remove ports and add nginx at deployment
    # env_file:
    #   - .env
    #   - .env.production
    ports:
      - "8000:8000"
    restart: always

  db:
    restart: always

  redis:
    restart: always
